Assignment 2 - Working with Pandas


Objective Learn to create and manipulate dataframes for data analysis.  


Instructions


Step 1 Install Pandas using:
pip install pandas


Step 2 Create a new Python script pandas_assignment.ipynb. Import Pandas and follow these steps:  


1. Create a DataFrame with the following data:  
  


  data = {
      'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
      'Age': [24, 27, 22, 32, 29],
      'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
      'Salary': [45000, 54000, 50000, 62000, 47000]
  }
  a. Print the first five rows of the DataFrame.  
  b. Get the summary statistics of the 'Age' and 'Salary' columns.  
  c. Calculate the average salary of employees in the 'HR' department.  


2. Add a new column, 'Bonus', which is 10% of the salary.  


3. Filter the DataFrame to show employees aged between 25 and 30.  


4. Group the data by 'Department' and calculate the average salary for each department.  


5. Sort the DataFrame by 'Salary' in ascending order and save the result to a new CSV file.

In [1]:
# importing pands library and set common alias 

import pandas as pd

# 1. Create a DataFrame with the following data:

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'Department': ['HR', 'Finance', 'IT', 'Marketing', 'HR'],
    'Salary': [45000, 54000, 50000, 62000, 47000]
}

In [3]:
df =  pd.DataFrame(data)

In [4]:
df

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

* pd.DataFrame(data) → converts the dictionary into a structured table (DataFrame).

 # 1a. Print the first five rows of the DataFrame.

In [5]:
df.head()

      Name  Age Department  Salary
0    Alice   24         HR   45000
1      Bob   27    Finance   54000
2  Charlie   22         IT   50000
3    Diana   32  Marketing   62000
4      Eve   29         HR   47000

* head() displays the first 5 rows by default.

* It helps us quickly verify that the DataFrame was created correctly.

# 1b. Get the summary statistics of the 'Age' and 'Salary' columns.

In [6]:
stats = round(df[['Age', 'Salary']].describe(),2)
stats

         Age    Salary
count   5.00      5.00
mean   26.80  51600.00
std     3.96   6730.53
min    22.00  45000.00
25%    24.00  47000.00
50%    27.00  50000.00
75%    29.00  54000.00
max    32.00  62000.00

* describe() provides summary statistics (count, mean, min, max, quartiles).

* Selecting columns using double brackets [['Age', 'Salary']] limits output to those two

# 1c. Calculate the average salary of employees in the 'HR' department.

In [7]:
hr_avg_sal = df[df['Department'] == 'HR']['Salary'].mean()
print("Average HR Salary:", hr_avg_sal)

Average HR Salary: 46000.0

* df['Department'] == 'HR' → filters rows where Department is HR.

* [‘Salary’].mean() selects only the Salary column and using mean() it will return average salary.

# 2. Add a new column, 'Bonus', which is 10% of the salary.

In [8]:
df['Bonus'] = df['Salary'] * 0.10

In [9]:
df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
1      Bob   27    Finance   54000  5400.0
2  Charlie   22         IT   50000  5000.0
3    Diana   32  Marketing   62000  6200.0
4      Eve   29         HR   47000  4700.0

* Creates a new column called Bonus.

* Multiplies each employee’s salary by 10% (0.10).

# 3. Filter the DataFrame to show employees aged between 25 and 30.

In [10]:
filtered_df = df[(df['Age']>=25) & (df['Age']<=30)]

In [11]:
filtered_df

  Name  Age Department  Salary   Bonus
1  Bob   27    Finance   54000  5400.0
4  Eve   29         HR   47000  4700.0

* Uses Boolean operators to select rows where age is between 25 and 30.

* The & symbol means AND (both conditions must be true).

# 4. Group the data by 'Department' and calculate the average salary for each department.

In [12]:
avg_salary_by_dept  = df.groupby('Department')['Salary'].mean()

In [13]:
avg_salary_by_dept

Department
Finance      54000.0
HR           46000.0
IT           50000.0
Marketing    62000.0
Name: Salary, dtype: float64

* groupby('Department') groups rows by department name.

* ['Salary'].mean() calculates the average salary per department.

# 5. Sort the DataFrame by 'Salary' in ascending order and save the result to a new CSV file.

In [14]:
sorted_df = df.sort_values(by='Salary', ascending=True)

In [15]:
sorted_df

      Name  Age Department  Salary   Bonus
0    Alice   24         HR   45000  4500.0
4      Eve   29         HR   47000  4700.0
2  Charlie   22         IT   50000  5000.0
1      Bob   27    Finance   54000  5400.0
3    Diana   32  Marketing   62000  6200.0

In [16]:
sorted_df.to_csv('sorted_employees.csv', index=False)

* sort_values(by='Salary', ascending=True) sorts rows in ascending order of Salary column.

* to_csv('sorted_employees.csv', index=False) saves the result to a CSV file without row numbers.